development:
  cloud_name: <%= ENV['CLOUDNAME'] %>
  api_key: <%= ENV['API_KEY'] %>
  api_secret: <%= ENV['API_SECRET'] %>
production:
  cloud_name: <%= ENV['CLOUDNAME'] %>
  api_key: <%= ENV['API_KEY'] %>
  api_secret: <%= ENV['API_SECRET'] %>
test:
  cloud_name: <%= ENV['CLOUDNAME'] %>
  api_key: <%= ENV['API_KEY'] %>
  api_secret: <%= ENV['API_SECRET'] %>